apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{ .Values.cluster.name }}
spec:
  clusterSize: {{ .Values.cluster.size }}
  clusterName: {{ .Values.cluster.name }}
  repository: {{ .Values.repository }}
  version: {{ .Values.version }}
  licenseKeySecretName: {{ .Release.Name }}-license-key
---
apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: {{ .Values.cluster.name }}-mc
spec:
  repository: 'hazelcast/management-center'
  version: '5.9.0'
  licenseKeySecretName: {{ .Release.Name }}-license-key
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
  - address: {{ .Values.cluster.name }}.{{ .Release.Namespace }}:5701
    name: {{ .Values.cluster.name }}